### ISSUE TITLE
Don't write to file on 404 Not Found

### ISSUE THREAD

**Issue by aklatzke** [Philosec/gicreator#1]
<img width="325" alt="screen shot 2018-04-30 at 10 59 44 pm" src="https://user-images.githubusercontent.com/1848868/39460616-6a8d25e6-4cca-11e8-9be3-962da2fd2c06.png">

I'm not certain what your preferred way of handling unfound ignore packages is, but for these that are dumping "404 not found" it would probably be best to leave them blank instead of pushing the 404 message into the template. 

The Mac one should at minimum (and probably only) blacklist .DS_Store's in every directory.

**Comment by shanepadgett** [comment]
This is actually two issues. Is something returns a 404 it should not be written and macOS should be returning a result. #6
